TrackingInventory/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using TrackingInventory.Areas.HelpPage.ModelDescriptions;
using TrackingInventory.Areas.HelpPage.Models;

namespace TrackingInventory.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

TrackingInventory/Controllers/UsersMVCController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using TrackingInventory.Models;
using TrackingInventory.CustomValidation;

namespace TrackingInventory.Controllers
{
    public class UsersMVCController : Controller
    {
        private TrackingInventoryContext db = new TrackingInventoryContext();

        // GET: UsersMVC
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: UsersMVC/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: UsersMVC/Create
       
        public ActionResult Create()
        {
            //ViewBag.RoleID = new SelectList(db.Roles, "RoleId", "RoleName");
            return View();
        }

        // POST: UsersMVC/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,UserName,FirstName,LastName,Password")] User user)
        {
            if (ModelState.IsValid)
            {
             
                var hashedPassword = Crypto.HashPassword(user.Password);
                user.Password = hashedPassword;
                user.Role = 02;
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.RoleID = new SelectList(db.Roles, "RoleId", "RoleName", user.RoleId);
            return View(user);
        }


      
        public ActionResult SignIn()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SignIn(SignInViewModel LogingUser)
        {
            var checkUserIfExists = db.Users.FirstOrDefault(u => u.UserName.Equals(LogingUser.UserName));
        
            
            if (ModelState.IsValid && checkUserIfExists != null)
            {
                bool verifyPassword = Crypto.VerifyHashedPassword(checkUserIfExists.Password, LogingUser.Password);
                if (verifyPassword == true)
                {

                    // creating authetication ticket
                    FormsAuthentication.SetAuthCookie(LogingUser.UserName, false);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    @ViewBag.Message = "Error.Ivalid login.";
                    return RedirectToAction("SignInFailure", "FundRaisers");
                }

            }

            ModelState.AddModelError("UserDoesNotExist", "Username or Password is Incorrect! Please try Again!!");
            return View(LogingUser);
        }


     
        [HttpPost]
        public JsonResult CheckForDuplication(string UserName)
        {
            var data = db.Users.Where(p => p.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            if (data != null)
            {
                return Json("Sorry, this name already exists", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: UsersMVC/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
      
        [HttpPost]
      
        public ActionResult Edit([Bind(Include = "UserID,UserName,FristName,LastName,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: UsersMVC/Delete/5

        [CustomUserAuthorize(Permission ="User")]
        public ActionResult Test()
        {
            return View();
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: UsersMVC/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult Logout()
        {
            // This is the predefined SignOut method in FormAuthentication :p
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");

        }
    }
}

TrackingInventory/Views/Shared/SharedPartialView.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    {
        @Html.AntiForgeryToken()
      
     

        <li class="pull-right">@Html.ActionLink("Sign Out", "Logout", "UsersMVC") </li>
        <li class="pull-right">@Html.ActionLink(HttpContext.Current.User.Identity.GetUserName(), "Home")</li>
     
    }
}
else
{
   
    <li class="pull-right">@Html.ActionLink("Sign Up", "Create", "UsersMVC")</li>
    <li class="pull-right">@Html.ActionLink("Sign In", "SignIn", "UsersMVC")</li>
   
}

TrackingInventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CONVERGENT</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container ">
        <div class="header">
          
            <div class="nav">
                <ul class="otis">
                  
                   
                    <li class="partial">@Html.Partial("SharedPartialView")</li>
                </ul>
            </div>
        </div>
        <div class="clear"></div>
        <div class=" body-content">
            @RenderBody()
        </div>
        <hr class="hr" />
        <footer>
            <span style=" margin-left:initial"><p>&copy; @DateTime.Now.Year - Team Origin </p></span>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>





















@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>*@